In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('customer.csv')

In [4]:
df.sample(6)

age  gender   review education purchased
28   48    Male     Poor    School        No
45   61    Male     Poor        PG       Yes
0    30  Female  Average    School        No
7    60  Female     Poor    School       Yes
24   16  Female  Average        PG       Yes
5    31  Female  Average    School       Yes

In [7]:
df = df.iloc[:,2:]

In [8]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [9]:
from sklearn.model_selection import train_test_split
X_test, X_train, y_test, y_train = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2)

In [10]:
X_train

review education
12     Poor    School
39     Poor        PG
34  Average    School
10     Good        UG
32  Average        UG
47     Good        PG
19     Poor        PG
6      Good    School
15     Poor        UG
46     Poor        PG

In [11]:
from sklearn.preprocessing import OrdinalEncoder

In [12]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']]) #CREATE OBJ, LIST INSIDE LIST PARAMETER

In [13]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [14]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [15]:
X_train

array([[0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [0., 1.],
       [0., 2.]])

In [16]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [17]:
from sklearn.preprocessing import LabelEncoder

In [19]:
le = LabelEncoder() # we can't choose order here

In [20]:
le.fit(y_train)

LabelEncoder()

In [21]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [23]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [24]:
y_train

array([0, 0, 0, 1, 1, 1, 1, 0, 0, 0])

In [25]:
y_test

array([1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1])

In [26]:
df.head(15)

review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes